import { chmod, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import type { CredentialReference } from "../../shared/credentials.js";

/**
 * The helper that AWS `credential_process` and Claude Code's
 * `awsCredentialExport` invoke from inside a capsule.
 *
 * It cannot be Node: the RunAsNode fuse is disabled (ADR 0006) and the helper
 * is spawned by the AWS client inside the sandbox, so it cannot be an Electron
 * utility process either. It is therefore a generated POSIX shell script using
 * a transport that is already present on each supported platform - `nc` is part
 * of the macOS base system, and `socat` is already a required Linux isolation
 * dependency.
 *
 * The helper holds no credential. It relays a session token and a reference id
 * and writes back whatever the main process returns.
 */
export const BROKER_TOKEN_VARIABLE = "OPSCAPSULE_BROKER_TOKEN";

export function createBrokerToken(): string {
  return randomBytes(32).toString("base64url");
}

function transportCommand(socketPath: string): string {
  if (process.platform === "linux") {
    return `socat - "UNIX-CONNECT:${socketPath}"`;
  }
  return `/usr/bin/nc -U "${socketPath}"`;
}

export function buildBrokerHelperScript(socketPath: string): string {
  return [
    "#!/bin/sh",
    "# Generated by OpsCapsule. Relays a credential request to the main",
    "# process. Contains no credential material.",
    "set -eu",
    "",
    'if [ "$#" -ne 1 ]; then',
    '  echo "usage: broker <credential-reference>" >&2',
    "  exit 64",
    "fi",
    "",
    `if [ -z "\${${BROKER_TOKEN_VARIABLE}:-}" ]; then`,
    '  echo "The broker session token is not present." >&2',
    "  exit 77",
    "fi",
    "",
    "# The token travels in the environment, never in argv, because argv is",
    "# readable by other processes owned by the same user.",
    `printf '{"token":"%s","referenceId":"%s"}\\n' "\${${BROKER_TOKEN_VARIABLE}}" "$1" \\`,
    `  | ${transportCommand(socketPath)}`,
    "",
  ].join("\n");
}

export async function writeBrokerHelper(
  path: string,
  socketPath: string,
): Promise<void> {
  await writeFile(path, buildBrokerHelperScript(socketPath), {
    encoding: "utf8",
    mode: 0o700,
  });
  await chmod(path, 0o700);
}
