import { chmod, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import type { CredentialReference } from "../../shared/credentials.js";

/**
 * The helper that AWS `credential_process` and Claude Code's
 * `awsCredentialExport` invoke from inside a capsule.
 *
 * It cannot be Node: the RunAsNode fuse is disabled (ADR 0006) and the helper
 * is spawned by the AWS client inside the sandbox, so it cannot be an Electron
 * utility process either. It is therefore a generated POSIX shell script using
 * a transport that is already present on each supported platform - `nc` is part
 * of the macOS base system, and `socat` is already a required Linux isolation
 * dependency.
 *
 * The helper holds no credential. It relays a session token and a reference id
 * and writes back whatever the main process returns.
 */
export const BROKER_TOKEN_VARIABLE = "OPSCAPSULE_BROKER_TOKEN";

export function createBrokerToken(): string {
  return randomBytes(32).toString("base64url");
}

function transportCommand(socketPath: string): string {
  if (process.platform === "linux") {
    return `socat - "UNIX-CONNECT:${socketPath}"`;
  }
  return `/usr/bin/nc -U "${socketPath}"`;
}

export function buildBrokerHelperScript(socketPath: string): string {
  return [
    "#!/bin/sh",
    "# Generated by OpsCapsule. Relays a credential request to the main",
    "# process. Contains no credential material.",
    "set -eu",
    "",
    'if [ "$#" -ne 1 ]; then',
    '  echo "usage: broker <credential-reference>" >&2',
    "  exit 64",
    "fi",
    "",
    `if [ -z "\${${BROKER_TOKEN_VARIABLE}:-}" ]; then`,
    '  echo "The broker session token is not present." >&2',
    "  exit 77",
    "fi",
    "",
    "# The token travels in the environment, never in argv, because argv is",
    "# readable by other processes owned by the same user.",
    `printf '{"token":"%s","referenceId":"%s"}\\n' "\${${BROKER_TOKEN_VARIABLE}}" "$1" \\`,
    `  | ${transportCommand(socketPath)}`,
    "",
  ].join("\n");
}

export async function writeBrokerHelper(
  path: string,
  socketPath: string,
): Promise<void> {
  await writeFile(path, buildBrokerHelperScript(socketPath), {
    encoding: "utf8",
    mode: 0o700,
  });
  await chmod(path, 0o700);
}

export const OPERATIONAL_PROFILE_NAME = "default";
export const INFERENCE_PROFILE_NAME = "opscapsule-inference";

export interface CapsuleAwsIdentities {
  readonly helperPath: string;
  readonly operational?: CredentialReference;
  readonly inference?: CredentialReference;
  readonly operationalRegion?: string;
}

/**
 * Builds the AWS config for a capsule. The operational identity is the default
 * profile; the inference identity is present under a name but is never the
 * default and is never referenced from the environment, because any AWS_*
 * variable reaching the agent also reaches the operational commands it spawns.
 */
export function buildCapsuleAwsConfig(identities: CapsuleAwsIdentities): string {
  const sections: string[] = [];

  if (identities.operational) {
    sections.push(
      `[${OPERATIONAL_PROFILE_NAME}]`,
      ...regionLine(identities.operational.region ?? identities.operationalRegion),
      `credential_process = ${credentialProcess(
        identities.helperPath,
        identities.operational,
      )}`,
    );
  }

  if (identities.inference) {
    if (identities.inference.id === identities.operational?.id) {
      throw new Error(
        "The inference identity must not reuse the operational credential reference.",
      );
    }
    if (sections.length > 0) {
      sections.push("");
    }
    sections.push(
      `[profile ${INFERENCE_PROFILE_NAME}]`,
      ...regionLine(identities.inference.region),
      `credential_process = ${credentialProcess(
        identities.helperPath,
        identities.inference,
      )}`,
    );
  }

  return sections.length > 0 ? `${sections.join("\n")}\n` : "";
}

function regionLine(region: string | undefined): string[] {
  return region ? [`region = ${region}`] : [];
}

function credentialProcess(
  helperPath: string,
  reference: CredentialReference,
): string {
  // The reference id is not secret and is validated against a strict
  // identifier pattern, so it is safe in argv. The session token is not.
  return `${helperPath} ${reference.id}`;
}
