import { chmod, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import type { CredentialReference } from "../../shared/credentials.js";
import {
  BROKER_REFERENCE_HEADER,
  BROKER_TOKEN_HEADER,
} from "./broker.js";

/**
 * The helper that AWS `credential_process` and Claude Code's
 * `awsCredentialExport` invoke from inside a capsule.
 *
 * It cannot be Node: the RunAsNode fuse is disabled (ADR 0006) and the helper
 * is spawned by the AWS client inside the sandbox, so it cannot be an Electron
 * utility process either. It is therefore a generated POSIX shell script.
 *
 * The transport is `curl --unix-socket`. An earlier version used `nc`, which
 * is quietly broken for this purpose: `nc` exits as soon as its stdin reaches
 * EOF and discards a response that has not already arrived. Resolving a real
 * AWS profile takes hundreds of milliseconds, so every genuine request was
 * lost. `curl` waits for the response, is present by default on macOS and
 * effectively every Linux distribution, and removes the per-platform split.
 *
 * The helper holds no credential. It relays a session token and a reference id
 * and writes back whatever the main process returns.
 */
export const BROKER_TOKEN_VARIABLE = "OPSCAPSULE_BROKER_TOKEN";

export function createBrokerToken(): string {
  return randomBytes(32).toString("base64url");
}

export function buildBrokerHelperScript(socketPath: string): string {
  return [
    "#!/bin/sh",
    "# Generated by OpsCapsule. Relays a credential request to the main",
    "# process. Contains no credential material.",
    "set -eu",
    "",
    'if [ "$#" -ne 1 ]; then',
    '  echo "usage: broker <credential-reference>" >&2',
    "  exit 64",
    "fi",
    "",
    `if [ -z "\${${BROKER_TOKEN_VARIABLE}:-}" ]; then`,
    '  echo "The broker session token is not present." >&2',
    "  exit 77",
    "fi",
    "",
    "# The token travels in a header sourced from the environment, never in",
    "# argv, which other processes owned by the same user can read.",
    "# --noproxy keeps the sandbox's own HTTP proxy settings out of a request",
    "# that never leaves the machine.",
    "exec /usr/bin/curl --silent --show-error --fail \\",
    '  --noproxy "*" \\',
    `  --unix-socket "${socketPath}" \\`,
    `  --header "${BROKER_TOKEN_HEADER}: \${${BROKER_TOKEN_VARIABLE}}" \\`,
    `  --header "${BROKER_REFERENCE_HEADER}: $1" \\`,
    "  http://localhost/credentials",
    "",
  ].join("\n");
}

export async function writeBrokerHelper(
  path: string,
  socketPath: string,
): Promise<void> {
  await writeFile(path, buildBrokerHelperScript(socketPath), {
    encoding: "utf8",
    mode: 0o700,
  });
  await chmod(path, 0o700);
}
