export const IPC = {
  listWorkspaces: "workspace:list",
  getWorkspace: "workspace:get",
  createWorkspace: "workspace:create",
  saveWorkspace: "workspace:save",
  deleteWorkspace: "workspace:delete",
  choosePath: "workspace:choose-path",
  inspectDirectory: "workspace:inspect-directory",
  inspectAgentConfiguration: "workspace:inspect-agent-configuration",
  discoverLocalResources: "workspace:discover-local-resources",
  checkTargetReadiness: "workspace:check-target-readiness",
  credentialStatus: "credential:status",
  credentialImport: "credential:import",
  credentialForget: "credential:forget",
  startWorkspace: "workspace:start",
  stopWorkspace: "workspace:stop",
  terminalAttach: "terminal:attach",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",
} as const;
